### ISSUE TITLE
Trying to install on bash

### ISSUE THREAD

**Issue by licsuj27** [ricardbejarano/graphql_exporter#3]
upon make command, 

find . -name '*.go' -exec gofmt -e -s -w {} +
CGO_ENABLED=0 go build -o bin/graphql_exporter
query.go:14:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
        /usr/lib/go-1.10/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
        /root/go/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
main.go:9:2: cannot find package "github.com/prometheus/client_golang/prometheus/promhttp" in any of:
        /usr/lib/go-1.10/src/github.com/prometheus/client_golang/prometheus/promhttp (from $GOROOT)
        /root/go/src/github.com/prometheus/client_golang/prometheus/promhttp (from $GOPATH)
query.go:16:2: cannot find package "github.com/ricardbejarano/go-graphql" in any of:
        /usr/lib/go-1.10/src/github.com/ricardbejarano/go-graphql (from $GOROOT)
        /root/go/src/github.com/ricardbejarano/go-graphql (from $GOPATH)
main.go:10:2: cannot find package "github.com/usewormhol/env" in any of:
        /usr/lib/go-1.10/src/github.com/usewormhol/env (from $GOROOT)
        /root/go/src/github.com/usewormhol/env (from $GOPATH)
Makefile:7: recipe for target 'build' failed
make: *** [build] Error 1

any ideas?

**Comment by ricardbejarano** [comment]
Hey @justin27c thanks for using `graphql_exporter` and for reaching out!

🎉 **Fortunately I know what's causing you trouble!** 🎉 

---
As you can see on [`go.mod`](https://github.com/ricardbejarano/graphql_exporter/blob/master/go.mod), this package is built using Go 1.16.
Now, that doesn't mean it won't work on older versions, but I aim at supporting Go >= 1.16.

Judging by your log output, seems as if your local Go copy is version 1.10.
I suggest you upgrade.

You can check the exact version by doing `go version` on your shell.

---
As an annex, I just built it using Go 1.16.3:

```
$ go version
go version go1.16.3 ***/***
$ make
find . -name '*.go' -exec gofmt -e -s -w {} +
CGO_ENABLED=0 go build -o bin/graphql_exporter
go: downloading github.com/prometheus/client_golang v1.9.0
go: downloading github.com/ricardbejarano/go-graphql v1.0.0
go: downloading github.com/usewormhol/env v1.0.0
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/common v0.15.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/prometheus/procfs v0.2.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading google.golang.org/protobuf v1.23.0
go: downloading golang.org/x/sys v0.0.0-20201214210602-f9fddec55a1e
$
```

Hope it helps!

**Comment by licsuj27** [comment]
Thanks worked successfully.
