### ISSUE TITLE
Port 9199 conflicts with officially supported Cloudflare exporter

### ISSUE THREAD

**Issue by jsnod** [ricardbejarano/graphql_exporter#6]
Per https://github.com/prometheus/prometheus/wiki/Default-port-allocations, port `9199` is reserved for the [Cloudflare Exporter](https://github.com/wehkamp/docker-prometheus-cloudflare-exporter). This GraphQL Exporter should coordinate with Prometheus to reserve a unique port in order to avoid conflicts.

**Comment by ricardbejarano** [comment]
This is actually on purpose.

This exporter began as a Cloudflare exporter with a wider scope than [wehkamp/docker-prometheus-cloudflare-exporter](https://github.com/wehkamp/docker-prometheus-cloudflare-exporter), which only works for Enterprise plans.

Some months into it, Cloudflare deprecated their old analytics API in favor of its new GraphQL one.
By adapting my old Cloudflare exporter to the new GraphQL API, I figured it'd be more versatile to just write a generic GraphQL exporter, which could be then used for Cloudflare or anything else.

In any case, changing the port now will break everyone's integration.
If there's conflict, I suggest you modify the [`EXPORTER_LISTEN_ADDR`](https://github.com/ricardbejarano/graphql_exporter/blob/master/main.go#L14) environment variable:

```bash
export EXPORTER_LISTEN_ADDR="0.0.0.0:12345"
```
