### ISSUE TITLE
Query endpoint always returns a gauge value of `1`

### ISSUE THREAD

**Issue by jsnod** [ricardbejarano/graphql_exporter#7]
Hi, I've got this exporter successfully querying against my GridQL endpoint, and it is returning the expected values, however, they arrive as a label rather than a value, and the metric value is always `1`:

```bash
curl -H 'Authorization: Token XXX' \
'https://my.server.com:9199/query?endpoint=https://my.api/v2/api/&query=<url_encoded_query>'
# HELP query_user_accounts_apps_logs_entries_data
# TYPE query_user_accounts_apps_logs_entries_data gauge
query_user_accounts_apps_logs_entries_data{accounts="0",apps="0",endpoint="https://my.api/v2/api/",entries="0",value="{\"data\": {\"latency\": 6226}, ...}}"} 1
```

This exporter seems to return the query results under the `value` label, but it doesn't present them as an actual metric value per the Prometheus format: `metric_name{metric_label1="abc",metric_label2="zxc"} 12345.34`

I was able to use Prometheus' `metric_relabel_configs` to extract the `latency` from inside the `value` label and put it into its own label, so now it looks like this in Prometheus:

```
query_user_accounts_apps_logs_entries_data{instance="localhost:9199", job="graphql_exporter", latency="6226", value="{"data": {"latency": 6226,...}}"}
```

However, I want to get the `latency` value into proper Prometheus format like so:

```
query_user_accounts_apps_logs_entries_data{instance="localhost:9199", job="graphql_exporter"} 6226
```

Currently every metric value is just `1` so there's nothing useful to graph in Grafana. Am I missing something? Or is there a bug here? How do I get all the values out of the `value` label and into actual metric values per Prometheus format? Thanks for your help!

**Comment by ricardbejarano** [comment]
What's the output of the GraphQL endpoint when queried manually? (e.g.: with `cURL`).

**Comment by jsnod** [comment]
> What's the output of the GraphQL endpoint when queried manually? (e.g.: with `cURL`).

The raw JSON returned looks like this:
```
{
  "data": {
    "user": {
      "accounts": [{
        "apps": [{
          "logs": {
            "entries": [{
              "data": "{\"data\": {\"app_id\": \"app-12345\", \"latency\": 2581, \"name\": \"My Thing\", \"permalink\": \"my-thing\"}, \"event\": \"question\", \"context\": {}, \"user_id\": \"u-12345\", \"trace_id\": \"tr-12345\", \"sensitive\": false, \"thread_id\": \"t-12345\", \"timestamp\": 1639168076172, \"integration_id\": \"thing\", \"parent_entry_ref\": {\"id\": \"12345-0\", \"data\": {\"thing_id\": \"thing.default\", \"thread_id\": \"t-12345\"}, \"ledger\": \"thing\"}}"
            }]
          }
        }]
      }]
    }
  }
}
```

I am wanting this to be a `latency` metric, in this case with a value of `2581`. It's a bit nasty that all the values get returned as a long string in the `data` field.

I was able to extract `latency` into its own Prometheus metric label with the following in `prometheus.xml`

```xml
metric_relabel_configs:
  - source_labels: [ value ]
    target_label: latency
    regex: .*latency\":[\s](\d+).*
    replacement: $1
    action: replace
```

But I need to get that into the actual metric value so that I can graph it in Grafana.

**Comment by ricardbejarano** [comment]
I'm afraid the problem here is the GraphQL endpoint.
If `latency` is an integer, it really shouldn't be returning it in a JSON-formatted string.

Working around it from the exporter not only is tough but would break backwards compatibility.

I suggest you (if possible) modify the endpoint into returning values in their proper types.
Otherwise, Grafana has great data transformation features, perhaps you can extract the value from there into a graph.

**Comment by ricardbejarano** [comment]
Is this ElasticSearch?
Isn't there a way to, at the GraphQL query, ask for just the `latency` field?
If the field is indexed shouldn't you be able to do that?

**Comment by jsnod** [comment]
Thanks, this is actually a GridQL endpoint which sits on top of Lucene, so I guess it's sort of a long lost sibling of Elasticsearch: https://docs.meya.ai/docs/gridql

I'm going to see if I can figure out how to make it return a single value in the expected datatype.
